### PR TITLE
feat: add mobile nav and ui changes in desktop nav accordingly

### LINKED ISSUE #31: Feature Request: Add horizontal navbar for mobile view
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe it.

Currently when you switch to mobile view, you have to scroll horizontally to be able to post a tweet.
Take a look :arrow_down: :

| layout_1 	| layout_1_1 	|
|--------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------------------	|
|                                                                                                                    	|                                                                                                                      	|

### Describe the solution you'd like.

It would be nice if we hide the sidebar and show a horizontal navbar at the top with an icon to open the sidebar
And perhaps add the logo and what not :sweat_smile: 

### Teachability, documentation, adoption, migration strategy.

_No response_

### What is the motivation / use case for changing the behavior?

I think it can facilitate posting tweets and improve user experince

### PR DESCRIPTION
**Pull request by yash91989201**
## Issue ticket number and link
fixes #31 

##Description
Added a mobile nav component and updated the existing the desktop nav , dynamically importing the component according to
the screen size.
Updated the desktop nav ui to look inline with the mobile nav ui.

##Screenshot

Desktop nav close :

desktop_menu-close

Desktop nav open:

desktop_menu_open

Mobile nav close:

mobile_menu-close

Mobile nav open:

mobile_menu-open

## Checklist before requesting a review
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by yash91989201** [comment]
Hey, @KyleTryon I have created a mobile navigation and have changed the desktop navigation to look inline with the mobile navigation . Please review the changes and let me know if there are any mistakes. Thankyou.

**Comment by TAKANOME-DEV** [comment]
@yash91989201 this looks great :+1: 

I have a couple of suggestions:
- avoid horizontal scroll on mobile screen when the sidebar is open
- extend the container to take the full width on mobile screen (the post button and the datetime input overflow)

**Comment by yash91989201** [comment]
Actually the post box is out of the scope of this issue (which was to create a mobile nav) for that I will create a new issue after this PR is accepted and merged . I think is good to keep a single agenda for a PR

**Comment by KyleTryon** [comment]
Excellent work @yash91989201! Thank you! I am checking this out locally.

**Review by KyleTryon — APPROVED** [review]

**Comment by KyleTryon** [comment]
Congrats and many thanks yous @yash91989201! Welcome to the contributor's list! Appreciate your great work.

**Comment by yash91989201** [comment]
I am very glad that I was able to add value to your project. Looking forward to more contributions in the future 😀

**Pull request merged**
